name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - id: build
        name: Build
        run: |
          yarn install
          yarn run lint
          yarn run build

      - name: Notify slack success
        if: steps.build.outcome == 'success' && github.ref == 'refs/heads/dev'
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel: builds
          status: SUCCESS
          color: good

      - name: Notify slack fail
        if: steps.build.outcome == 'failure' && github.ref == 'refs/heads/dev'
        uses: voxmedia/github-action-slack-notify-build@v1.1.2
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel: builds
          status: FAILED
          color: danger
